<?php

// $id = date('d/m/Y',trim($_POST['fecha_ini']));
// $id1 = date('d/m/Y',trim($_POST['fecha_fin']));
 $id = trim($_POST['fecha_ini']);
 $id1 =trim($_POST['fecha_fin']);

 $ptoeb = trim($_POST['ptoeb']);
 
 
include("clases/gui/gui.class.php");
include("configuracion.php");
include("funciones/funciones.php");
header('Content-type: application/vnd.ms-excel');
header("Content-Disposition: attachment; filename=archivo.xls");
header("Pragma: no-cache");
header("Expires: 0");
	$connection = pg_connect("host=$sql_host port=$puerto dbname=$sql_db user=$sql_usuario password=$sql_pass") or die("No se realiz&oacute la conexi&oacute;n Detalles:".pg_last_error());

	if ($ptoeb==diario)
  	{
	
	 $sql="select * from diario where fechax  >= '$id' and fechax <= '$id1' order by fechax";
	//$sql="select * from diario where to_date(fecha, 'DD/MM/YYYY') >= '$id' and to_date(fecha, 'DD/MM/YYYY') <= '$id1' order by fecha";
 	$result = pg_query ($connection, $sql ) or die("Error en la consulta SQL");
	$registros= pg_num_rows($result);
	
	//mostrar resultados
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>P/T </th>\n";
	echo "<th><font color=green> Jose</th>\n";
	echo "<th><font color=green>Antonio</th>\n";
	echo "<th><font color=green>Anzoategui</th>\n";
	echo "</table border=1>\n";
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>5 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>7 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>11 am</th>\n";
    echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>1 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>5 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>9 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>11 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "</table border=1>\n";
		
	echo "<table border=1>\n";
	echo "<th><font color=green>FECHA</th>\n";
	echo "<th><font color=green>EB L-1</th>\n";
    echo "<th><font color=green>EB L-2</th>\n";
	echo "<th><font color=green>EB ZS</th>\n";
	echo "<th><font color=green>EB T-T</th>\n";
	echo "<th><font color=green>PC T E</th>\n";
	echo "<th><font color=green>PC T S</th>\n";
	echo "<th><font color=green>PC C E</th>\n";
	echo "<th><font color=green>PC C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>PM T E</th>\n";
    echo "<th><font color=green>PM T S</th>\n";
	echo "<th><font color=green>PM C E</th>\n";
	echo "<th><font color=green>PM C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>QCANAL E</th>\n";
	echo "<th><font color=green>QT-T E</th>\n";
	echo "<th><font color=green>PL-1</th>\n";
	echo "<th><font color=green>PL-2</th>\n";
	echo "<th><font color=green>PZS</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>COTA RIO</th>\n";
	echo "<th><font color=green>C RESIDUAL</th>\n";
	echo "<th><font color=green>EB L-1</th>\n";
    echo "<th><font color=green>EB L-2</th>\n";
	echo "<th><font color=green>EB ZS</th>\n";
	echo "<th><font color=green>EB T-T</th>\n";
	echo "<th><font color=green>PC T E</th>\n";
	echo "<th><font color=green>PC T S</th>\n";
	echo "<th><font color=green>PC C E</th>\n";
	echo "<th><font color=green>PC C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>PM T E</th>\n";
    echo "<th><font color=green>PM T S</th>\n";
	echo "<th><font color=green>PM C E</th>\n";
	echo "<th><font color=green>PM C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>QCANAL E</th>\n";
	echo "<th><font color=green>QT-T E</th>\n";
	echo "<th><font color=green>PL-1</th>\n";
	echo "<th><font color=green>PL-2</th>\n";
	echo "<th><font color=green>PZS</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>COTA RIO</th>\n";
	echo "<th><font color=green>C RESIDUAL</th>\n";
	echo "<th><font color=green>EB L-1</th>\n";
    echo "<th><font color=green>EB L-2</th>\n";
	echo "<th><font color=green>EB ZS</th>\n";
	echo "<th><font color=green>EB T-T</th>\n";
	echo "<th><font color=green>PC T E</th>\n";
	echo "<th><font color=green>PC T S</th>\n";
	echo "<th><font color=green>PC C E</th>\n";
	echo "<th><font color=green>PC C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>PM T E</th>\n";
    echo "<th><font color=green>PM T S</th>\n";
	echo "<th><font color=green>PM C E</th>\n";
	echo "<th><font color=green>PM C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>QCANAL E</th>\n";
	echo "<th><font color=green>QT-T E</th>\n";
	echo "<th><font color=green>PL-1</th>\n";
	echo "<th><font color=green>PL-2</th>\n";
	echo "<th><font color=green>PZS</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>COTA RIO</th>\n";
	echo "<th><font color=green>C RESIDUAL</th>\n";
	echo "<th><font color=green>EB L-1</th>\n";
    echo "<th><font color=green>EB L-2</th>\n";
	echo "<th><font color=green>EB ZS</th>\n";
	echo "<th><font color=green>EB T-T</th>\n";
	echo "<th><font color=green>PC T E</th>\n";
	echo "<th><font color=green>PC T S</th>\n";
	echo "<th><font color=green>PC C E</th>\n";
	echo "<th><font color=green>PC C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>PM T E</th>\n";
    echo "<th><font color=green>PM T S</th>\n";
	echo "<th><font color=green>PM C E</th>\n";
	echo "<th><font color=green>PM C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>QCANAL E</th>\n";
	echo "<th><font color=green>QT-T E</th>\n";
	echo "<th><font color=green>PL-1</th>\n";
	echo "<th><font color=green>PL-2</th>\n";
	echo "<th><font color=green>PZS</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>COTA RIO</th>\n";
	echo "<th><font color=green>C RESIDUAL</th>\n";
	echo "<th><font color=green>EB L-1</th>\n";
    echo "<th><font color=green>EB L-2</th>\n";
	echo "<th><font color=green>EB ZS</th>\n";
	echo "<th><font color=green>EB T-T</th>\n";
	echo "<th><font color=green>PC T E</th>\n";
	echo "<th><font color=green>PC T S</th>\n";
	echo "<th><font color=green>PC C E</th>\n";
	echo "<th><font color=green>PC C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>PM T E</th>\n";
    echo "<th><font color=green>PM T S</th>\n";
	echo "<th><font color=green>PM C E</th>\n";
	echo "<th><font color=green>PM C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>QCANAL E</th>\n";
	echo "<th><font color=green>QT-T E</th>\n";
	echo "<th><font color=green>PL-1</th>\n";
	echo "<th><font color=green>PL-2</th>\n";
	echo "<th><font color=green>PZS</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>COTA RIO</th>\n";
	echo "<th><font color=green>C RESIDUAL</th>\n";
	echo "<th><font color=green>EB L-1</th>\n";
    echo "<th><font color=green>EB L-2</th>\n";
	echo "<th><font color=green>EB ZS</th>\n";
	echo "<th><font color=green>EB T-T</th>\n";
	echo "<th><font color=green>PC T E</th>\n";
	echo "<th><font color=green>PC T S</th>\n";
	echo "<th><font color=green>PC C E</th>\n";
	echo "<th><font color=green>PC C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>PM T E</th>\n";
    echo "<th><font color=green>PM T S</th>\n";
	echo "<th><font color=green>PM C E</th>\n";
	echo "<th><font color=green>PM C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>QCANAL E</th>\n";
	echo "<th><font color=green>QT-T E</th>\n";
	echo "<th><font color=green>PL-1</th>\n";
	echo "<th><font color=green>PL-2</th>\n";
	echo "<th><font color=green>PZS</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>COTA RIO</th>\n";
	echo "<th><font color=green>C RESIDUAL</th>\n";
	echo "<th><font color=green>EB L-1</th>\n";
    echo "<th><font color=green>EB L-2</th>\n";
	echo "<th><font color=green>EB ZS</th>\n";
	echo "<th><font color=green>EB T-T</th>\n";
	echo "<th><font color=green>PC T E</th>\n";
	echo "<th><font color=green>PC T S</th>\n";
	echo "<th><font color=green>PC C E</th>\n";
	echo "<th><font color=green>PC C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>PM T E</th>\n";
    echo "<th><font color=green>PM T S</th>\n";
	echo "<th><font color=green>PM C E</th>\n";
	echo "<th><font color=green>PM C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>QCANAL E</th>\n";
	echo "<th><font color=green>QT-T E</th>\n";
	echo "<th><font color=green>PL-1</th>\n";
	echo "<th><font color=green>PL-2</th>\n";
	echo "<th><font color=green>PZS</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>COTA RIO</th>\n";
	echo "<th><font color=green>C RESIDUAL</th>\n";
	
	
	
	   
	for ($i=0;$i<$registros;$i++)
	{
		$row = pg_fetch_array ($result,$i );
		echo "</tr>\n";
		echo "<td>" . $row["fecha"] . "</font></td>\n";
		echo "<td>" . $row["a1"] . "</font></td>\n";
		echo "<td>" . $row["a2"] . "</font></td>\n";
		echo "<td>" . $row["a3"] . "</font></td>\n";
		echo "<td>" . $row["a4"] . "</font></td>\n";
		echo "<td>" . $row["a5"] . "</font></td>\n";
		echo "<td>" . $row["a6"] . "</font></td>\n";
		echo "<td>" . $row["a7"] . "</font></td>\n";
		echo "<td>" . $row["a8"] . "</font></td>\n";
		echo "<td>" . $row["a9"] . "</font></td>\n";
		echo "<td>" . $row["a10"] . "</font></td>\n";
		echo "<td>" . $row["a11"] . "</font></td>\n";
		echo "<td>" . $row["a12"] . "</font></td>\n";
		echo "<td>" . $row["a13"] . "</font></td>\n";
		echo "<td>" . $row["a14"] . "</font></td>\n";
		echo "<td>" . $row["a15"] . "</font></td>\n";
		echo "<td>" . $row["a16"] . "</font></td>\n";
		echo "<td>" . $row["a17"] . "</font></td>\n";
		echo "<td>" . $row["a18"] . "</font></td>\n";
		echo "<td>" . $row["a19"] . "</font></td>\n";
		echo "<td>" . $row["a20"] . "</font></td>\n";
		echo "<td>" . $row["a21"] . "</font></td>\n";
		echo "<td>" . $row["a22"] . "</font></td>\n";
		echo "<td>" . $row["b1"] . "</font></td>\n";
		echo "<td>" . $row["b2"] . "</font></td>\n";
		echo "<td>" . $row["b3"] . "</font></td>\n";
		echo "<td>" . $row["b4"] . "</font></td>\n";
		echo "<td>" . $row["b5"] . "</font></td>\n";
		echo "<td>" . $row["b6"] . "</font></td>\n";
		echo "<td>" . $row["b7"] . "</font></td>\n";
		echo "<td>" . $row["b8"] . "</font></td>\n";
		echo "<td>" . $row["b9"] . "</font></td>\n";
		echo "<td>" . $row["b10"] . "</font></td>\n";
		echo "<td>" . $row["b11"] . "</font></td>\n";
		echo "<td>" . $row["b12"] . "</font></td>\n";
		echo "<td>" . $row["b13"] . "</font></td>\n";
		echo "<td>" . $row["b14"] . "</font></td>\n";
		echo "<td>" . $row["b15"] . "</font></td>\n";
		echo "<td>" . $row["b16"] . "</font></td>\n";
		echo "<td>" . $row["b17"] . "</font></td>\n";
		echo "<td>" . $row["b18"] . "</font></td>\n";
		echo "<td>" . $row["b19"] . "</font></td>\n";
		echo "<td>" . $row["b20"] . "</font></td>\n";
		echo "<td>" . $row["b21"] . "</font></td>\n";
		echo "<td>" . $row["b22"] . "</font></td>\n";
		echo "<td>" . $row["c1"] . "</font></td>\n";
		echo "<td>" . $row["c2"] . "</font></td>\n";
		echo "<td>" . $row["c3"] . "</font></td>\n";
		echo "<td>" . $row["c4"] . "</font></td>\n";
		echo "<td>" . $row["c5"] . "</font></td>\n";
		echo "<td>" . $row["c6"] . "</font></td>\n";
		echo "<td>" . $row["c7"] . "</font></td>\n";
		echo "<td>" . $row["c8"] . "</font></td>\n";
		echo "<td>" . $row["c9"] . "</font></td>\n";
		echo "<td>" . $row["c10"] . "</font></td>\n";
		echo "<td>" . $row["c11"] . "</font></td>\n";
		echo "<td>" . $row["c12"] . "</font></td>\n";
		echo "<td>" . $row["c13"] . "</font></td>\n";
		echo "<td>" . $row["c14"] . "</font></td>\n";
		echo "<td>" . $row["c15"] . "</font></td>\n";
		echo "<td>" . $row["c16"] . "</font></td>\n";
		echo "<td>" . $row["c17"] . "</font></td>\n";
		echo "<td>" . $row["c18"] . "</font></td>\n";
		echo "<td>" . $row["c19"] . "</font></td>\n";
		echo "<td>" . $row["c20"] . "</font></td>\n";
		echo "<td>" . $row["c21"] . "</font></td>\n";
		echo "<td>" . $row["c22"] . "</font></td>\n";
		echo "<td>" . $row["d1"] . "</font></td>\n";
		echo "<td>" . $row["d2"] . "</font></td>\n";
		echo "<td>" . $row["d3"] . "</font></td>\n";
		echo "<td>" . $row["d4"] . "</font></td>\n";
		echo "<td>" . $row["d5"] . "</font></td>\n";
		echo "<td>" . $row["d6"] . "</font></td>\n";
		echo "<td>" . $row["d7"] . "</font></td>\n";
		echo "<td>" . $row["d8"] . "</font></td>\n";
		echo "<td>" . $row["d9"] . "</font></td>\n";
		echo "<td>" . $row["d10"] . "</font></td>\n";
		echo "<td>" . $row["d11"] . "</font></td>\n";
		echo "<td>" . $row["d12"] . "</font></td>\n";
		echo "<td>" . $row["d13"] . "</font></td>\n";
		echo "<td>" . $row["d14"] . "</font></td>\n";
		echo "<td>" . $row["d15"] . "</font></td>\n";
		echo "<td>" . $row["d16"] . "</font></td>\n";
		echo "<td>" . $row["d17"] . "</font></td>\n";
		echo "<td>" . $row["d18"] . "</font></td>\n";
		echo "<td>" . $row["d19"] . "</font></td>\n";
		echo "<td>" . $row["d20"] . "</font></td>\n";
		echo "<td>" . $row["d21"] . "</font></td>\n";
		echo "<td>" . $row["d22"] . "</font></td>\n";
		echo "<td>" . $row["e1"] . "</font></td>\n";
		echo "<td>" . $row["e2"] . "</font></td>\n";
		echo "<td>" . $row["e3"] . "</font></td>\n";
		echo "<td>" . $row["e4"] . "</font></td>\n";
		echo "<td>" . $row["e5"] . "</font></td>\n";
		echo "<td>" . $row["e6"] . "</font></td>\n";
		echo "<td>" . $row["e7"] . "</font></td>\n";
		echo "<td>" . $row["e8"] . "</font></td>\n";
		echo "<td>" . $row["e9"] . "</font></td>\n";
		echo "<td>" . $row["e10"] . "</font></td>\n";
		echo "<td>" . $row["e11"] . "</font></td>\n";
		echo "<td>" . $row["e12"] . "</font></td>\n";
		echo "<td>" . $row["e13"] . "</font></td>\n";
		echo "<td>" . $row["e14"] . "</font></td>\n";
		echo "<td>" . $row["e15"] . "</font></td>\n";
		echo "<td>" . $row["e16"] . "</font></td>\n";
		echo "<td>" . $row["e17"] . "</font></td>\n";
		echo "<td>" . $row["e18"] . "</font></td>\n";
		echo "<td>" . $row["e19"] . "</font></td>\n";
		echo "<td>" . $row["e20"] . "</font></td>\n";
		echo "<td>" . $row["e21"] . "</font></td>\n";
		echo "<td>" . $row["e22"] . "</font></td>\n";
		echo "<td>" . $row["f1"] . "</font></td>\n";
		echo "<td>" . $row["f2"] . "</font></td>\n";
		echo "<td>" . $row["f3"] . "</font></td>\n";
		echo "<td>" . $row["f4"] . "</font></td>\n";
		echo "<td>" . $row["f5"] . "</font></td>\n";
		echo "<td>" . $row["f6"] . "</font></td>\n";
		echo "<td>" . $row["f7"] . "</font></td>\n";
		echo "<td>" . $row["f8"] . "</font></td>\n";
		echo "<td>" . $row["f9"] . "</font></td>\n";
		echo "<td>" . $row["f10"] . "</font></td>\n";
		echo "<td>" . $row["f11"] . "</font></td>\n";
		echo "<td>" . $row["f12"] . "</font></td>\n";
		echo "<td>" . $row["f13"] . "</font></td>\n";
		echo "<td>" . $row["f14"] . "</font></td>\n";
		echo "<td>" . $row["f15"] . "</font></td>\n";
		echo "<td>" . $row["f16"] . "</font></td>\n";
		echo "<td>" . $row["f17"] . "</font></td>\n";
		echo "<td>" . $row["f18"] . "</font></td>\n";
		echo "<td>" . $row["f19"] . "</font></td>\n";
		echo "<td>" . $row["f20"] . "</font></td>\n";
		echo "<td>" . $row["f21"] . "</font></td>\n";
		echo "<td>" . $row["f22"] . "</font></td>\n";
		echo "<td>" . $row["g1"] . "</font></td>\n";
		echo "<td>" . $row["g2"] . "</font></td>\n";
		echo "<td>" . $row["g3"] . "</font></td>\n";
		echo "<td>" . $row["g4"] . "</font></td>\n";
		echo "<td>" . $row["g5"] . "</font></td>\n";
		echo "<td>" . $row["g6"] . "</font></td>\n";
		echo "<td>" . $row["g7"] . "</font></td>\n";
		echo "<td>" . $row["g8"] . "</font></td>\n";
		echo "<td>" . $row["g9"] . "</font></td>\n";
		echo "<td>" . $row["g10"] . "</font></td>\n";
		echo "<td>" . $row["g11"] . "</font></td>\n";
		echo "<td>" . $row["g12"] . "</font></td>\n";
		echo "<td>" . $row["g13"] . "</font></td>\n";
		echo "<td>" . $row["g14"] . "</font></td>\n";
		echo "<td>" . $row["g15"] . "</font></td>\n";
		echo "<td>" . $row["g16"] . "</font></td>\n";
		echo "<td>" . $row["g17"] . "</font></td>\n";
		echo "<td>" . $row["g18"] . "</font></td>\n";
		echo "<td>" . $row["g19"] . "</font></td>\n";
		echo "<td>" . $row["g20"] . "</font></td>\n";
		echo "<td>" . $row["g21"] . "</font></td>\n";
		echo "<td>" . $row["g22"] . "</font></td>\n";
		echo "</tr>\n";
	} 
	}
	
	else if ($ptoeb==diario3)
  	{
		
		 $sql="select * from diario3 where fechax  >= '$id' and fechax <= '$id1' order by fechax";
		//$sql="select * from diario3 where to_date(fecha, 'DD/MM/YYYY') >= '$id' and to_date(fecha, 'DD/MM/YYYY') <= '$id1' order by fecha";
 	$result = pg_query ($connection, $sql ) or die("Error en la consulta SQL");
	$registros= pg_num_rows($result);
		
	//mostrar resultados
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>P/T </th>\n";
	echo "<th><font color=green>El Rincon</th>\n";
	echo "</table border=1>\n";
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>5 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>7 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>11 am</th>\n";
    echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>1 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>5 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>9 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>11 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "</table border=1>\n";
		
	echo "<table border=1>\n";
	echo "<th><font color=green>FECHA</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
    echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>TANQ</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
	echo "<th><font color=green>POLIM</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
    echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>TANQ</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
	echo "<th><font color=green>POLIM</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
    echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>TANQ</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
	echo "<th><font color=green>POLIM</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
    echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>TANQ</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
	echo "<th><font color=green>POLIM</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
    echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>TANQ</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
	echo "<th><font color=green>POLIM</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
    echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>TANQ</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
	echo "<th><font color=green>POLIM</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
    echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>TANQ</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
	echo "<th><font color=green>POLIM</th>\n";
    
		   
	for ($i=0;$i<$registros;$i++)
	{
		$row = pg_fetch_array ($result,$i );
		echo "</tr>\n";
		echo "<td>" . $row["fecha"] . "</font></td>\n";
		echo "<td>" . $row["a1"] . "</font></td>\n";
		echo "<td>" . $row["a2"] . "</font></td>\n";
		echo "<td style=mso-number-format:'@';>" . $row["a3"] . "</font></td>\n";
		echo "<td>" . $row["a4"] . "</font></td>\n";
		echo "<td>" . $row["a5"] . "</font></td>\n";
		echo "<td>" . $row["a6"] . "</font></td>\n";
		echo "<td>" . $row["a7"] . "</font></td>\n";
		echo "<td>" . $row["a8"] . "</font></td>\n";
		echo "<td>" . $row["a9"] . "</font></td>\n";
		echo "<td>" . $row["a10"] . "</font></td>\n";
		echo "<td>" . $row["b1"] . "</font></td>\n";
		echo "<td>" . $row["b2"] . "</font></td>\n";
		echo "<td style=mso-number-format:'@';>" . $row["b3"] . "</font></td>\n";
		echo "<td>" . $row["b4"] . "</font></td>\n";
		echo "<td>" . $row["b5"] . "</font></td>\n";
		echo "<td>" . $row["b6"] . "</font></td>\n";
		echo "<td>" . $row["b7"] . "</font></td>\n";
		echo "<td>" . $row["b8"] . "</font></td>\n";
		echo "<td>" . $row["b9"] . "</font></td>\n";
		echo "<td>" . $row["b10"] . "</font></td>\n";
		echo "<td>" . $row["c1"] . "</font></td>\n";
		echo "<td>" . $row["c2"] . "</font></td>\n";
		echo "<td style=mso-number-format:'@';>" . $row["c3"] . "</font></td>\n";
		echo "<td>" . $row["c4"] . "</font></td>\n";
		echo "<td>" . $row["c5"] . "</font></td>\n";
		echo "<td>" . $row["c6"] . "</font></td>\n";
		echo "<td>" . $row["c7"] . "</font></td>\n";
		echo "<td>" . $row["c8"] . "</font></td>\n";
		echo "<td>" . $row["c9"] . "</font></td>\n";
		echo "<td>" . $row["c10"] . "</font></td>\n";
		echo "<td>" . $row["d1"] . "</font></td>\n";
		echo "<td>" . $row["d2"] . "</font></td>\n";
		echo "<td style=mso-number-format:'@';>" . $row["d3"] . "</font></td>\n";
		echo "<td>" . $row["d4"] . "</font></td>\n";
		echo "<td>" . $row["d5"] . "</font></td>\n";
		echo "<td>" . $row["d6"] . "</font></td>\n";
		echo "<td>" . $row["d7"] . "</font></td>\n";
		echo "<td>" . $row["d8"] . "</font></td>\n";
		echo "<td>" . $row["d9"] . "</font></td>\n";
		echo "<td>" . $row["d10"] . "</font></td>\n";
		echo "<td>" . $row["e1"] . "</font></td>\n";
		echo "<td>" . $row["e2"] . "</font></td>\n";
		echo "<td style=mso-number-format:'@';>" . $row["e3"] . "</font></td>\n";
		echo "<td>" . $row["e4"] . "</font></td>\n";
		echo "<td>" . $row["e5"] . "</font></td>\n";
		echo "<td>" . $row["e6"] . "</font></td>\n";
		echo "<td>" . $row["e7"] . "</font></td>\n";
		echo "<td>" . $row["e8"] . "</font></td>\n";
		echo "<td>" . $row["e9"] . "</font></td>\n";
		echo "<td>" . $row["e10"] . "</font></td>\n";
		echo "<td>" . $row["f1"] . "</font></td>\n";
		echo "<td>" . $row["f2"] . "</font></td>\n";
		echo "<td style=mso-number-format:'@';>" . $row["f3"] . "</font></td>\n";
		echo "<td>" . $row["f4"] . "</font></td>\n";
		echo "<td>" . $row["f5"] . "</font></td>\n";
		echo "<td>" . $row["f6"] . "</font></td>\n";
		echo "<td>" . $row["f7"] . "</font></td>\n";
		echo "<td>" . $row["f8"] . "</font></td>\n";
		echo "<td>" . $row["f9"] . "</font></td>\n";
		echo "<td>" . $row["f10"] . "</font></td>\n";
		echo "<td>" . $row["g1"] . "</font></td>\n";
		echo "<td>" . $row["g2"] . "</font></td>\n";
		echo "<td style=mso-number-format:'@';>" . $row["g3"] . "</font></td>\n";
		echo "<td>" . $row["g4"] . "</font></td>\n";
		echo "<td>" . $row["g5"] . "</font></td>\n";
		echo "<td>" . $row["g6"] . "</font></td>\n";
		echo "<td>" . $row["g7"] . "</font></td>\n";
		echo "<td>" . $row["g8"] . "</font></td>\n";
		echo "<td>" . $row["g9"] . "</font></td>\n";
		echo "<td>" . $row["g10"] . "</font></td>\n";
		echo "</tr>\n";
	} 
	}
		
	else if ($ptoeb==diario4)
  	{

	 $sql="select * from diario4 where fechax  >= '$id' and fechax <= '$id1' order by fechax";
	//$sql="select * from diario4 where to_date(fecha, 'DD/MM/YYYY') >= '$id' and to_date(fecha, 'DD/MM/YYYY') <= '$id1' order by fecha";
 	$result = pg_query ($connection, $sql ) or die("Error en la consulta SQL");
	$registros= pg_num_rows($result);
	
	//mostrar resultados
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>P/T </th>\n";
	echo "<th><font color=green>Santa</th>\n";
	echo "<th><font color=green>Clara</th>\n";
	echo "</table border=1>\n";
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>5 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>7 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>11 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>1 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>5 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>9 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>11 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "</table border=1>\n";
		
	echo "<table border=1>\n";
	echo "<th><font color=green>FECHA</th>\n";
	echo "<th><font color=green>PIRITU EQ</th>\n";
    echo "<th><font color=green>PIRITU CAUDAL</th>\n";
	echo "<th><font color=green>PIRITU PRESION</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
	echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>CLORO RESIDUAL</th>\n";
	echo "<th><font color=green>EQ EMBALSE</th>\n";
	echo "<th><font color=green>CLARINES EQ</th>\n";
	echo "<th><font color=green>CLARINES CAUDAL</th>\n";
	echo "<th><font color=green>CLARINES PRESION</th>\n";
	echo "<th><font color=green>PIRITU EQ</th>\n";
    echo "<th><font color=green>PIRITU CAUDAL</th>\n";
	echo "<th><font color=green>PIRITU PRESION</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
	echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>CLORO RESIDUAL</th>\n";
	echo "<th><font color=green>EQ EMBALSE</th>\n";
	echo "<th><font color=green>CLARINES EQ</th>\n";
	echo "<th><font color=green>CLARINES CAUDAL</th>\n";
	echo "<th><font color=green>CLARINES PRESION</th>\n";
	echo "<th><font color=green>PIRITU EQ</th>\n";
    echo "<th><font color=green>PIRITU CAUDAL</th>\n";
	echo "<th><font color=green>PIRITU PRESION</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
	echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>CLORO RESIDUAL</th>\n";
	echo "<th><font color=green>EQ EMBALSE</th>\n";
	echo "<th><font color=green>CLARINES EQ</th>\n";
	echo "<th><font color=green>CLARINES CAUDAL</th>\n";
	echo "<th><font color=green>CLARINES PRESION</th>\n";
	echo "<th><font color=green>PIRITU EQ</th>\n";
    echo "<th><font color=green>PIRITU CAUDAL</th>\n";
	echo "<th><font color=green>PIRITU PRESION</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
	echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>CLORO RESIDUAL</th>\n";
	echo "<th><font color=green>EQ EMBALSE</th>\n";
	echo "<th><font color=green>CLARINES EQ</th>\n";
	echo "<th><font color=green>CLARINES CAUDAL</th>\n";
	echo "<th><font color=green>CLARINES PRESION</th>\n";
	echo "<th><font color=green>PIRITU EQ</th>\n";
    echo "<th><font color=green>PIRITU CAUDAL</th>\n";
	echo "<th><font color=green>PIRITU PRESION</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
	echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>CLORO RESIDUAL</th>\n";
	echo "<th><font color=green>EQ EMBALSE</th>\n";
	echo "<th><font color=green>CLARINES EQ</th>\n";
	echo "<th><font color=green>CLARINES CAUDAL</th>\n";
	echo "<th><font color=green>CLARINES PRESION</th>\n";
	echo "<th><font color=green>PIRITU EQ</th>\n";
    echo "<th><font color=green>PIRITU CAUDAL</th>\n";
	echo "<th><font color=green>PIRITU PRESION</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
	echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>CLORO RESIDUAL</th>\n";
	echo "<th><font color=green>EQ EMBALSE</th>\n";
	echo "<th><font color=green>CLARINES EQ</th>\n";
	echo "<th><font color=green>CLARINES CAUDAL</th>\n";
	echo "<th><font color=green>CLARINES PRESION</th>\n";
	echo "<th><font color=green>PIRITU EQ</th>\n";
    echo "<th><font color=green>PIRITU CAUDAL</th>\n";
	echo "<th><font color=green>PIRITU PRESION</th>\n";
	echo "<th><font color=green>Q ENTRADA</th>\n";
	echo "<th><font color=green>Q SALIDA</th>\n";
	echo "<th><font color=green>T E</th>\n";
	echo "<th><font color=green>T S</th>\n";
	echo "<th><font color=green>C E</th>\n";
	echo "<th><font color=green>C S</th>\n";
	echo "<th><font color=green>PAC</th>\n";
	echo "<th><font color=green>SULF AL</th>\n";
    echo "<th><font color=green>POLIMERO</th>\n";
	echo "<th><font color=green>CLORO RESIDUAL</th>\n";
	echo "<th><font color=green>EQ EMBALSE</th>\n";
	echo "<th><font color=green>CLARINES EQ</th>\n";
	echo "<th><font color=green>CLARINES CAUDAL</th>\n";
	echo "<th><font color=green>CLARINES PRESION</th>\n";
			   
	for ($i=0;$i<$registros;$i++)
	{
		$row = pg_fetch_array ($result,$i );
		echo "</tr>\n";
		echo "<td>" . $row["fecha"] . "</font></td>\n";
		echo "<td>" . $row["a1"] . "</font></td>\n";
		echo "<td>" . $row["a2"] . "</font></td>\n";
		echo "<td>" . $row["a3"] . "</font></td>\n";
		echo "<td>" . $row["a4"] . "</font></td>\n";
		echo "<td>" . $row["a5"] . "</font></td>\n";
		echo "<td>" . $row["a6"] . "</font></td>\n";
		echo "<td>" . $row["a7"] . "</font></td>\n";
		echo "<td>" . $row["a8"] . "</font></td>\n";
		echo "<td>" . $row["a9"] . "</font></td>\n";
		echo "<td>" . $row["a10"] . "</font></td>\n";
		echo "<td>" . $row["a11"] . "</font></td>\n";
		echo "<td>" . $row["a12"] . "</font></td>\n";
		echo "<td>" . $row["a13"] . "</font></td>\n";
		echo "<td>" . $row["a14"] . "</font></td>\n";
		echo "<td>" . $row["b1"] . "</font></td>\n";
		echo "<td>" . $row["b2"] . "</font></td>\n";
		echo "<td>" . $row["b3"] . "</font></td>\n";
		echo "<td>" . $row["c1"] . "</font></td>\n";
		echo "<td>" . $row["c2"] . "</font></td>\n";
		echo "<td>" . $row["c3"] . "</font></td>\n";
		echo "<td>" . $row["c4"] . "</font></td>\n";
		echo "<td>" . $row["c5"] . "</font></td>\n";
		echo "<td>" . $row["c6"] . "</font></td>\n";
		echo "<td>" . $row["c7"] . "</font></td>\n";
		echo "<td>" . $row["c8"] . "</font></td>\n";
		echo "<td>" . $row["c9"] . "</font></td>\n";
		echo "<td>" . $row["c10"] . "</font></td>\n";
		echo "<td>" . $row["c11"] . "</font></td>\n";
		echo "<td>" . $row["c12"] . "</font></td>\n";
		echo "<td>" . $row["c13"] . "</font></td>\n";
		echo "<td>" . $row["c14"] . "</font></td>\n";
		echo "<td>" . $row["d1"] . "</font></td>\n";
		echo "<td>" . $row["d2"] . "</font></td>\n";
		echo "<td>" . $row["d3"] . "</font></td>\n";
		echo "<td>" . $row["e1"] . "</font></td>\n";
		echo "<td>" . $row["e2"] . "</font></td>\n";
		echo "<td>" . $row["e3"] . "</font></td>\n";
		echo "<td>" . $row["e4"] . "</font></td>\n";
		echo "<td>" . $row["e5"] . "</font></td>\n";
		echo "<td>" . $row["e6"] . "</font></td>\n";
		echo "<td>" . $row["e7"] . "</font></td>\n";
		echo "<td>" . $row["e8"] . "</font></td>\n";
		echo "<td>" . $row["e9"] . "</font></td>\n";
		echo "<td>" . $row["e10"] . "</font></td>\n";
		echo "<td>" . $row["e11"] . "</font></td>\n";
		echo "<td>" . $row["e12"] . "</font></td>\n";
		echo "<td>" . $row["e13"] . "</font></td>\n";
		echo "<td>" . $row["e14"] . "</font></td>\n";
		echo "<td>" . $row["f1"] . "</font></td>\n";
		echo "<td>" . $row["f2"] . "</font></td>\n";
		echo "<td>" . $row["f3"] . "</font></td>\n";
		echo "<td>" . $row["g1"] . "</font></td>\n";
		echo "<td>" . $row["g2"] . "</font></td>\n";
		echo "<td>" . $row["g3"] . "</font></td>\n";
		echo "<td>" . $row["g4"] . "</font></td>\n";
		echo "<td>" . $row["g5"] . "</font></td>\n";
		echo "<td>" . $row["g6"] . "</font></td>\n";
		echo "<td>" . $row["g7"] . "</font></td>\n";
		echo "<td>" . $row["g8"] . "</font></td>\n";
		echo "<td>" . $row["g9"] . "</font></td>\n";
		echo "<td>" . $row["g10"] . "</font></td>\n";
		echo "<td>" . $row["g11"] . "</font></td>\n";
		echo "<td>" . $row["g12"] . "</font></td>\n";
		echo "<td>" . $row["g13"] . "</font></td>\n";
		echo "<td>" . $row["g14"] . "</font></td>\n";
		echo "<td>" . $row["h1"] . "</font></td>\n";
		echo "<td>" . $row["h2"] . "</font></td>\n";
		echo "<td>" . $row["h3"] . "</font></td>\n";
		echo "<td>" . $row["i1"] . "</font></td>\n";
		echo "<td>" . $row["i2"] . "</font></td>\n";
		echo "<td>" . $row["i3"] . "</font></td>\n";
		echo "<td>" . $row["i4"] . "</font></td>\n";
		echo "<td>" . $row["i5"] . "</font></td>\n";
		echo "<td>" . $row["i6"] . "</font></td>\n";
		echo "<td>" . $row["i7"] . "</font></td>\n";
		echo "<td>" . $row["i8"] . "</font></td>\n";
		echo "<td>" . $row["i9"] . "</font></td>\n";
		echo "<td>" . $row["i10"] . "</font></td>\n";
		echo "<td>" . $row["i11"] . "</font></td>\n";
		echo "<td>" . $row["i12"] . "</font></td>\n";
		echo "<td>" . $row["i13"] . "</font></td>\n";
		echo "<td>" . $row["i14"] . "</font></td>\n";
		echo "<td>" . $row["j1"] . "</font></td>\n";
		echo "<td>" . $row["j2"] . "</font></td>\n";
		echo "<td>" . $row["j3"] . "</font></td>\n";
		echo "<td>" . $row["k1"] . "</font></td>\n";
		echo "<td>" . $row["k2"] . "</font></td>\n";
		echo "<td>" . $row["k3"] . "</font></td>\n";
		echo "<td>" . $row["k4"] . "</font></td>\n";
		echo "<td>" . $row["k5"] . "</font></td>\n";
		echo "<td>" . $row["k6"] . "</font></td>\n";
		echo "<td>" . $row["k7"] . "</font></td>\n";
		echo "<td>" . $row["k8"] . "</font></td>\n";
		echo "<td>" . $row["k9"] . "</font></td>\n";
		echo "<td>" . $row["k10"] . "</font></td>\n";
		echo "<td>" . $row["k11"] . "</font></td>\n";
		echo "<td>" . $row["k12"] . "</font></td>\n";
		echo "<td>" . $row["k13"] . "</font></td>\n";
		echo "<td>" . $row["k14"] . "</font></td>\n";
		echo "<td>" . $row["l1"] . "</font></td>\n";
		echo "<td>" . $row["l2"] . "</font></td>\n";
		echo "<td>" . $row["l3"] . "</font></td>\n";
		echo "<td>" . $row["m1"] . "</font></td>\n";
		echo "<td>" . $row["m2"] . "</font></td>\n";
		echo "<td>" . $row["m3"] . "</font></td>\n";
		echo "<td>" . $row["m4"] . "</font></td>\n";
		echo "<td>" . $row["m5"] . "</font></td>\n";
		echo "<td>" . $row["m6"] . "</font></td>\n";
		echo "<td>" . $row["m7"] . "</font></td>\n";
		echo "<td>" . $row["m8"] . "</font></td>\n";
		echo "<td>" . $row["m9"] . "</font></td>\n";
		echo "<td>" . $row["m10"] . "</font></td>\n";
		echo "<td>" . $row["m11"] . "</font></td>\n";
		echo "<td>" . $row["m12"] . "</font></td>\n";
		echo "<td>" . $row["m13"] . "</font></td>\n";
		echo "<td>" . $row["m14"] . "</font></td>\n";
		echo "<td>" . $row["n1"] . "</font></td>\n";
		echo "<td>" . $row["n2"] . "</font></td>\n";
		echo "<td>" . $row["n3"] . "</font></td>\n";
		echo "</tr>\n";
	} 
	}
	
	if ($ptoeb==diario5)
  	{
		
    $sql="select * from diario5 where fechax  >= '$id' and fechax <= '$id1' order by fechax";
	//$sql="select * from diario5 where to_date(fecha, 'DD/MM/YYYY') >= '$id' and to_date(fecha, 'DD/MM/YYYY') <= '$id1' order by fecha";
 	$result = pg_query ($connection, $sql ) or die("Error en la consulta SQL");
	$registros= pg_num_rows($result);
	
	//mostrar resultados
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>E/B </th>\n";
	echo "<th><font color=green>Curaguaro</th>\n";
	echo "</table border=1>\n";
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>5 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>7 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green>11 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>1 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>5 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green>9 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>11 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "</table border=1>\n";
		
	echo "<table border=1>\n";
	echo "<th><font color=green>FECHA</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>PS</th>\n";
	echo "<th><font color=green>PD</th>\n";
	echo "<th><font color=green>CANAL E</th>\n";
	echo "<th><font color=green>CARATAL S</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>PS</th>\n";
	echo "<th><font color=green>PD</th>\n";
	echo "<th><font color=green>CANAL E</th>\n";
	echo "<th><font color=green>CARATAL S</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>PS</th>\n";
	echo "<th><font color=green>PD</th>\n";
	echo "<th><font color=green>CANAL E</th>\n";
	echo "<th><font color=green>CARATAL S</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>PS</th>\n";
	echo "<th><font color=green>PD</th>\n";
	echo "<th><font color=green>CANAL E</th>\n";
	echo "<th><font color=green>CARATAL S</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>PS</th>\n";
	echo "<th><font color=green>PD</th>\n";
	echo "<th><font color=green>CANAL E</th>\n";
	echo "<th><font color=green>CARATAL S</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>PS</th>\n";
	echo "<th><font color=green>PD</th>\n";
	echo "<th><font color=green>CANAL E</th>\n";
	echo "<th><font color=green>CARATAL S</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>PS</th>\n";
	echo "<th><font color=green>PD</th>\n";
	echo "<th><font color=green>CANAL E</th>\n";
	echo "<th><font color=green>CARATAL S</th>\n";
	
	
	   
	for ($i=0;$i<$registros;$i++)
	{
		$row = pg_fetch_array ($result,$i );
		echo "</tr>\n";
		echo "<td>" . $row["fecha"] . "</font></td>\n";
		echo "<td>" . $row["a1"] . "</font></td>\n";
		echo "<td>" . $row["a2"] . "</font></td>\n";
		echo "<td>" . $row["a3"] . "</font></td>\n";
		echo "<td>" . $row["a4"] . "</font></td>\n";
		echo "<td>" . $row["a5"] . "</font></td>\n";
		echo "<td>" . $row["a6"] . "</font></td>\n";
		echo "<td>" . $row["a7"] . "</font></td>\n";
		echo "<td>" . $row["b1"] . "</font></td>\n";
		echo "<td>" . $row["b2"] . "</font></td>\n";
		echo "<td>" . $row["b3"] . "</font></td>\n";
		echo "<td>" . $row["b4"] . "</font></td>\n";
		echo "<td>" . $row["b5"] . "</font></td>\n";
		echo "<td>" . $row["b6"] . "</font></td>\n";
		echo "<td>" . $row["b7"] . "</font></td>\n";
		echo "<td>" . $row["c1"] . "</font></td>\n";
		echo "<td>" . $row["c2"] . "</font></td>\n";
		echo "<td>" . $row["c3"] . "</font></td>\n";
		echo "<td>" . $row["c4"] . "</font></td>\n";
		echo "<td>" . $row["c5"] . "</font></td>\n";
		echo "<td>" . $row["c6"] . "</font></td>\n";
		echo "<td>" . $row["c7"] . "</font></td>\n";
		echo "<td>" . $row["d1"] . "</font></td>\n";
		echo "<td>" . $row["d2"] . "</font></td>\n";
		echo "<td>" . $row["d3"] . "</font></td>\n";
		echo "<td>" . $row["d4"] . "</font></td>\n";
		echo "<td>" . $row["d5"] . "</font></td>\n";
		echo "<td>" . $row["d6"] . "</font></td>\n";
		echo "<td>" . $row["d7"] . "</font></td>\n";
		echo "<td>" . $row["e1"] . "</font></td>\n";
		echo "<td>" . $row["e2"] . "</font></td>\n";
		echo "<td>" . $row["e3"] . "</font></td>\n";
		echo "<td>" . $row["e4"] . "</font></td>\n";
		echo "<td>" . $row["e5"] . "</font></td>\n";
		echo "<td>" . $row["e6"] . "</font></td>\n";
		echo "<td>" . $row["e7"] . "</font></td>\n";
		echo "<td>" . $row["f1"] . "</font></td>\n";
		echo "<td>" . $row["f2"] . "</font></td>\n";
		echo "<td>" . $row["f3"] . "</font></td>\n";
		echo "<td>" . $row["f4"] . "</font></td>\n";
		echo "<td>" . $row["f5"] . "</font></td>\n";
		echo "<td>" . $row["f6"] . "</font></td>\n";
		echo "<td>" . $row["f7"] . "</font></td>\n";
		echo "<td>" . $row["g1"] . "</font></td>\n";
		echo "<td>" . $row["g2"] . "</font></td>\n";
		echo "<td>" . $row["g3"] . "</font></td>\n";
		echo "<td>" . $row["g4"] . "</font></td>\n";
		echo "<td>" . $row["g5"] . "</font></td>\n";
		echo "<td>" . $row["g6"] . "</font></td>\n";
		echo "<td>" . $row["g7"] . "</font></td>\n";
		
		echo "</tr>\n";
	} 
	}
	
	else if ($ptoeb==diario6)
  	{

	 $sql="select * from diario6 where fechax  >= '$id' and fechax <= '$id1' order by fechax";
	 echo $sql;
	//$sql="select * from diario6 where fecha  >= '$id' and fecha <= '$id1' order by fecha";
//	$sql="select * from diario6 where to_date(fecha, 'DD/MM/YYYY') >= '$id' and to_date(fecha, 'DD/MM/YYYY') <= '$id1' order by fecha";
	
 	$result = pg_query ($connection, $sql ) or die("Error en la consulta SQL");
	$registros= pg_num_rows($result);
	
	//mostrar resultados
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>E/B El Yai</th>\n";
	echo "</table border=1>\n";
	
	echo "<table border=1>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>5 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>7 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>11 am</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>1 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>5 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>9 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "<th><font color=green>11 pm</th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
    echo "<th><font color=green></th>\n";
	echo "<th><font color=green></th>\n";
	echo "</table border=1>\n";
		
	echo "<table border=1>\n";
	echo "<th><font color=green>FECHA</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>P(m.c.a)</th>\n";
	echo "<th><font color=green>(Lbs)</th>\n";
	echo "<th><font color=green>Q (L/s)</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>P(m.c.a)</th>\n";
	echo "<th><font color=green>(Lbs)</th>\n";
	echo "<th><font color=green>Q (L/s)</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>P(m.c.a)</th>\n";
	echo "<th><font color=green>(Lbs)</th>\n";
	echo "<th><font color=green>Q (L/s)</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>P(m.c.a)</th>\n";
	echo "<th><font color=green>(Lbs)</th>\n";
	echo "<th><font color=green>Q (L/s)</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>P(m.c.a)</th>\n";
	echo "<th><font color=green>(Lbs)</th>\n";
	echo "<th><font color=green>Q (L/s)</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>P(m.c.a)</th>\n";
	echo "<th><font color=green>(Lbs)</th>\n";
	echo "<th><font color=green>Q (L/s)</th>\n";
	echo "<th><font color=green>EQ 1</th>\n";
    echo "<th><font color=green>EQ 2</th>\n";
	echo "<th><font color=green>EQ 3</th>\n";
	echo "<th><font color=green>P(m.c.a)</th>\n";
	echo "<th><font color=green>(Lbs)</th>\n";
	echo "<th><font color=green>Q (L/s)</th>\n";
		   
	for ($i=0;$i<$registros;$i++)
	{
		$row = pg_fetch_array ($result,$i );
		echo "</tr>\n";
		echo "<td>" . $row["fecha"] . "</font></td>\n";
		echo "<td>" . $row["a1"] . "</font></td>\n";
		echo "<td>" . $row["a2"] . "</font></td>\n";
		echo "<td>" . $row["a3"] . "</font></td>\n";
		echo "<td>" . $row["a4"] . "</font></td>\n";
		echo "<td>" . $row["a5"] . "</font></td>\n";
		echo "<td>" . $row["a6"] . "</font></td>\n";
		echo "<td>" . $row["b1"] . "</font></td>\n";
		echo "<td>" . $row["b2"] . "</font></td>\n";
		echo "<td>" . $row["b3"] . "</font></td>\n";
		echo "<td>" . $row["b4"] . "</font></td>\n";
		echo "<td>" . $row["b5"] . "</font></td>\n";
		echo "<td>" . $row["b6"] . "</font></td>\n";
		echo "<td>" . $row["c1"] . "</font></td>\n";
		echo "<td>" . $row["c2"] . "</font></td>\n";
		echo "<td>" . $row["c3"] . "</font></td>\n";
		echo "<td>" . $row["c4"] . "</font></td>\n";
		echo "<td>" . $row["c5"] . "</font></td>\n";
		echo "<td>" . $row["c6"] . "</font></td>\n";
		echo "<td>" . $row["d1"] . "</font></td>\n";
		echo "<td>" . $row["d2"] . "</font></td>\n";
		echo "<td>" . $row["d3"] . "</font></td>\n";
		echo "<td>" . $row["d4"] . "</font></td>\n";
		echo "<td>" . $row["d5"] . "</font></td>\n";
		echo "<td>" . $row["d6"] . "</font></td>\n";
		echo "<td>" . $row["e1"] . "</font></td>\n";
		echo "<td>" . $row["e2"] . "</font></td>\n";
		echo "<td>" . $row["e3"] . "</font></td>\n";
		echo "<td>" . $row["e4"] . "</font></td>\n";
		echo "<td>" . $row["e5"] . "</font></td>\n";
		echo "<td>" . $row["e6"] . "</font></td>\n";
		echo "<td>" . $row["f1"] . "</font></td>\n";
		echo "<td>" . $row["f2"] . "</font></td>\n";
		echo "<td>" . $row["f3"] . "</font></td>\n";
		echo "<td>" . $row["f4"] . "</font></td>\n";
		echo "<td>" . $row["f5"] . "</font></td>\n";
		echo "<td>" . $row["f6"] . "</font></td>\n";
		echo "<td>" . $row["g1"] . "</font></td>\n";
		echo "<td>" . $row["g2"] . "</font></td>\n";
		echo "<td>" . $row["g3"] . "</font></td>\n";
		echo "<td>" . $row["g4"] . "</font></td>\n";
		echo "<td>" . $row["g5"] . "</font></td>\n";
		echo "<td>" . $row["g6"] . "</font></td>\n";
		echo "</tr>\n";
	} 
	}

?>